### ISSUE TITLE
Message: Class "Akeeba\Plugin\WebServices\ARS\Extension\ARS" not found

### ISSUE THREAD

**Issue by kulbabskyy** [akeeba/release-system#232]
Hello Nicholas, 

I have enabled Admin Tools reports and fond the issue while random bots accessing the https://site.com/api/index.php
I tried to follow this URL and i see the error message: "Class "Akeeba\Plugin\WebServices\ARS\Extension\ARS" not found"
I runing latest ARS on Joomla 4.4.3 and PHP 8.1.24

Here is a content of the Admin Tools Report:

```
A PHP Exception occurred on your site. Here you can find the stack trace:

Exception Type: Error
File: /var/www/user/data/www/site.com/plugins/webservices/ars/services/provider.php
Line: 26
Message: Class "Akeeba\Plugin\WebServices\ARS\Extension\ARS" not found

#0 /var/www/user/data/www/site.com/libraries/vendor/joomla/di/src/ContainerResource.php(182): Joomla\DI\ServiceProviderInterface@anonymous->{closure}(Object(Joomla\DI\Container))
#1 /var/www/user/data/www/site.com/libraries/vendor/joomla/di/src/Container.php(96): Joomla\DI\ContainerResource->getInstance()
#2 /var/www/user/data/www/site.com/libraries/src/Extension/ExtensionManagerTrait.php(177): Joomla\DI\Container->get('Joomla\\CMS\\Exte...')
#3 /var/www/user/data/www/site.com/libraries/src/Extension/ExtensionManagerTrait.php(99): Joomla\CMS\Application\CMSApplication->loadExtension('Joomla\\CMS\\Exte...', 'ars:webservices', '/var/www/user...')
#4 /var/www/user/data/www/site.com/libraries/src/Plugin/PluginHelper.php(232): Joomla\CMS\Application\CMSApplication->bootPlugin('ars', 'webservices')
#5 /var/www/user/data/www/site.com/libraries/src/Plugin/PluginHelper.php(192): Joomla\CMS\Plugin\PluginHelper::import(Object(stdClass), true, Object(Joomla\Event\Dispatcher))
#6 /var/www/user/data/www/site.com/libraries/src/Application/ApiApplication.php(230): Joomla\CMS\Plugin\PluginHelper::importPlugin('webservices')
#7 /var/www/user/data/www/site.com/libraries/src/Application/ApiApplication.php(106): Joomla\CMS\Application\ApiApplication->route()
#8 /var/www/user/data/www/site.com/libraries/src/Application/CMSApplication.php(293): Joomla\CMS\Application\ApiApplication->doExecute()
#9 /var/www/user/data/www/site.com/api/includes/app.php(53): Joomla\CMS\Application\CMSApplication->execute()
#10 /var/www/user/data/www/site.com/api/index.php(31): require_once('/var/www/user...')
#11 {main}
```

Can you help me please to solve it?

**Comment by nikosdion** [comment]
Make sure the "Webservices - ARS" plugin is installed correctly in `plugins/webservices/ars`.

Delete `administrator/cache/autoload_psr4.php`.

**Comment by kulbabskyy** [comment]
deleting `administrator/cache/autoload_psr4.php` solves the issue, 
Thank you so much!
